import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const app = await readFile(new URL('../App.tsx', import.meta.url), 'utf8')
const view = await readFile(new URL('../components/BigPictureView.tsx', import.meta.url), 'utf8')
const css = await readFile(new URL('../components/BigPictureView.css', import.meta.url), 'utf8')
const capabilities = await readFile(new URL('../../src-tauri/capabilities/default.json', import.meta.url), 'utf8')
const lifecycle = await readFile(new URL('./bigPictureMode.ts', import.meta.url), 'utf8').catch(() => '')

assert.ok(capabilities.includes('core:window:allow-set-fullscreen'), 'Big Picture must be allowed to enter native fullscreen')
assert.ok(capabilities.includes('core:window:allow-is-fullscreen'), 'Big Picture must be allowed to snapshot native fullscreen state')
assert.ok(capabilities.includes('core:window:allow-current-monitor'), 'Big Picture fullscreen fallback must be allowed to read the current monitor')
assert.ok(capabilities.includes('core:window:allow-set-always-on-top'), 'Big Picture fullscreen fallback must be allowed above the Windows taskbar')
assert.ok(capabilities.includes('core:window:allow-is-always-on-top'), 'Big Picture must restore the previous z-order policy')
assert.ok(capabilities.includes('core:window:allow-outer-position'), 'Big Picture fallback must snapshot and restore window geometry')
assert.ok(capabilities.includes('core:window:allow-inner-position'), 'Big Picture fallback must measure the real client-area origin')
assert.ok(capabilities.includes('core:window:allow-is-resizable'), 'Big Picture must snapshot the resize-frame state')
assert.ok(capabilities.includes('core:window:allow-set-resizable'), 'Big Picture must temporarily remove the Windows resize frame')
assert.ok(lifecycle.includes('setFullscreen(true)'), 'native Big Picture helper must request fullscreen on enter')
assert.ok(lifecycle.includes('setFullscreen(session.previousFullscreen)'), 'native Big Picture helper must restore the previous fullscreen state')
assert.ok(lifecycle.includes("session.mode = 'borderless-fallback'"), 'Big Picture must include a monitor-sized fallback when native fullscreen is incomplete')
assert.ok(lifecycle.includes('currentMonitor()'), 'Big Picture fallback must target the current physical monitor')
assert.ok(lifecycle.includes('setAlwaysOnTop(true)'), 'Big Picture must temporarily own z-order above the Windows taskbar')
assert.ok(lifecycle.includes('nearlyFillsMonitor'), 'Big Picture must verify that native fullscreen actually fills the monitor')
assert.ok(lifecycle.includes('innerPosition()'), 'Windows fallback must calibrate the WebView client area instead of only the outer window')
assert.ok(lifecycle.includes('setResizable(false)'), 'Windows fallback must remove the invisible resize frame while active')
assert.ok(lifecycle.includes('previousInnerSize'), 'window restore must snapshot the same INNER-size coordinate system used by setSize()')
assert.ok(view.includes("classList.add('big-picture-document-active')"), 'Big Picture must force an opaque full-WebView surface while mounted')
assert.ok(view.includes('scrollIntoView') && view.includes("inline: 'center'"), 'Big Picture carousel must center the active card using native scrolling')
assert.ok(view.includes('new ResizeObserver(syncImmediate)'), 'carousel must recenter after native fullscreen/DPI viewport changes')
assert.ok(view.includes("--bp-end-gutter"), 'carousel must derive end gutters from its actual viewport width')
assert.ok(css.includes('mask-image: none'), 'Big Picture carousel must not mask/cut cover art at the viewport edges')
assert.ok(css.includes('scrollbar-width: none'), 'Big Picture carousel scrolling must remain visually clean')
assert.ok(app.includes("'entering' | 'active' | 'exiting'"), 'App must expose an explicit Big Picture lifecycle state')
assert.ok(!app.includes("phase={bigPicturePhase === 'closed' ? 'active' : bigPicturePhase}"), 'render branch must not re-check closed after isBigPictureMode narrows the phase')
assert.ok(app.includes('phase={bigPicturePhase}'), 'Big Picture must receive the already-narrowed lifecycle phase directly')
assert.ok(app.includes('onPlayGame='), 'App must wire Big Picture Play to launcher game launch flow')
assert.ok(view.includes('onPlayGame: (gameId: string) => void'), 'Big Picture must expose a real launch callback')
assert.ok(view.includes('pressedEdge(0)') && view.includes('launchActive() // A / Cross'), 'gamepad A/Cross must launch the active game')
assert.ok(view.includes('pressedEdge(1)') && view.includes('// B / Circle') && view.includes('else onExit()'), 'gamepad B/Circle must close overlays or exit Big Picture')
assert.ok(view.includes('pressedEdge(4)') && view.includes('pressedEdge(5)'), 'gamepad shoulder buttons must navigate the carousel')
assert.ok(css.includes('--theme-accent'), 'Big Picture accents must inherit Color Studio')
assert.ok(css.includes('--theme-modal-bg'), 'Big Picture overlays must inherit themed modal surfaces')
assert.ok(css.includes('.bp-cinematic-curtain'), 'Big Picture must have a dedicated cinematic transition layer')
assert.ok(css.includes('@media (prefers-reduced-motion: reduce)'), 'Big Picture CSS must respect reduced motion')

console.log('native Big Picture contract PASS')
